http:
  middlewares:
    crowdsec:
      plugin:
        crowdsec-bouncer-traefik-plugin:
          enabled: true
          logLevel: INFO
          crowdsecLapiKey: 6GkolLs/hZ1RJIAf5X6mkCEaha+U7wnrbduCwz2sOxM
          crowdsecLapiHost: crowdsec:8080
          crowdsecAppsecEnabled: false
          crowdsecAppsecHost: crowdsec:7422
          crowdsecAppsecFailureBlock: true
          crowdsecAppsecUnreachableBlock: true
